from app import db
from . import Utils


class Classroom(db.Model):
    # Don't touch this, it's managed
    __tablename__ = "classrooms"
    _id = db.Column(db.Integer, primary_key=True, name='id')
    uuid = db.Column(db.String(40), nullable=False, default=Utils.str_uuid4)
    # Attributes
    name = db.Column(db.String(20), nullable=False)
    building = db.Column(db.String(50), nullable=True)

    @db.validates("uuid")
    def uuid_edit_blocker(self, key, value):
        if self.uuid:  # Already exists
            raise ValueError("UUID is autogenerated and can not be modified!")
        return value

    def __init__(self, name, **kwargs):
        self.name = name
        super(Classroom, self).__init__(**kwargs)

    def __repr__(self):
        return f"Classroom {self.name}"
